version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: master
    reviewers:
      - gkampitakis
    labels:
      - dependabot
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
