language: node_js
node_js:
  - node

branches:
  only:
    - master
    - type=pull_request

cache:
  npm: false

before_install:
  - npm install

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
