version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
    default_reviewers:
      - 'gkampitakis'
    target_branch: 'master'
    default_labels:
      - 'dependabot'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
